import type { Metadata } from 'next'
import '../styles/globals.scss'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
    weight: ['400', '500', '600', '800'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Quiz App',
    // description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={poppins.className}>{children}</body>
        </html>
    )
}
